Часть 1 

1

а:

 A*B=4*2 и 4*2
 B*A=4*2 и 4*2

 Произведение не определены
 
б:

 A*B=2*5 и 5*3
 произведение определено, размерность полученной матрицы 2*3
 B*A=5*3 и 2*5
 произведение не определено

в:

 A*B=8*3 и 3*8
 произведение определено, размерность полученной матрицы 8*8
 B*A=3*8 и 8*3, 
 произведение определено, размерность полученной матрицы 3*3

г:

 A*B,B*A 
 оба произведение определены, размерность полученной матрицы 4*4

2

In [1]:
import numpy as np

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Сумма: A + B\n{A + B}')
print(f'Произведение: AB\n{np.dot(A, B)}')

Сумма: A + B
[[ 5 -3]
 [ 3  5]]
Произведение: AB
[[  4 -11]
 [ 12  -3]]


3

In [4]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2 ,-1]])
C = np.array([[2 ,-4],[1, 1]])

B2 = -2*B

print(f"Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 для матриц 𝐴 = \n{3*A + B2 + 4*C}\n")

Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 для матриц 𝐴 = 
[[ 11  -5]
 [  9 -12]]



4

In [6]:
A = np.array([[4, 1], [5, -2], [2, 3]])
AT = A.T
print(f'Матрица AA^T\n{np.dot(A, AT)}')
print(f'Матрица A^T*A\n{np.dot(AT, A)}')

Матрица AA^T
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица A^T*A
[[45  0]
 [ 0 14]]


Часть 2

1

а)

In [7]:
A = np.array([[4, 1], [5, -2]])
print(f'Определитель: sin^2(x)+cos^2(x) = 1')

Определитель: sin^2(x)+cos^2(x) = 1


б)

In [8]:
B = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Определитель: 4 * 5 * 9 = 180')
print(f'Определитель: {np.linalg.det(B):.0f}')

Определитель: 4 * 5 * 9 = 180
Определитель: 180


в)

In [12]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Определитель: {np.linalg.det(C):.0f}')

Определитель: 0


2

а) $det(A^{2})$ = 16;

б) $det(A^{T})$ = 4;
    из свойства определителей, определитель транспонированной матрицы равен определителю исходной

в) $det(2A)$ = $det(A)$* 2^n.
    в данном случае матрица А умножается на 2, тогда опредилитель данной матрицы умножается на 2 в степени колл-ва строк в матрице.

3

Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю. Если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю. Т.к. первая строка = (-2) умножить на вторую строку, т.е. они линейно зависимы, то определитель = 0

In [11]:
J = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель: {np.linalg.det(J):.0f}')

Определитель: 0


4

In [13]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

print(f'{a}')
print(f'Ранг матрицы: {np.linalg.matrix_rank(a)}')

[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы: 2


In [14]:
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'{b}')
print(f'Ранг матрицы: {np.linalg.matrix_rank(b)}')

[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы: 3
